### ISSUE TITLE
Test For Map and Number Copy Function

### ISSUE THREAD

**Issue by EgehanYaglici** [GMT-458-Web-GIS/personal-web-page-EgehanYaglici#1]
In this stage ı can not see the map on GitHub page and copy the phone number. These functions are working on local host. 

Possible issues are:

1) Clipboard API maybe can't work on my safari for copying the number
2) Leaflet.js and map data must also be loaded via HTTPS. Using HTTP can cause security issues and resources not loading.

**Comment by barancck** [comment]
**Deployment of an Older Version**

It appears that there is no script for map representation or associated functions in your app.js file. This likely indicates that you deployed an older version that did not yet include the map functionality.
<img width="994" alt="image" src="https://github.com/user-attachments/assets/f70655f8-5a8d-433e-bb64-0892d16968a6">

**Comment by EgehanYaglici** [comment]
app.js updated via original one. 

For the copying part ı solve that too, it is just copying first string not the actual number. thx
